### ISSUE TITLE
Missing string values from row

### ISSUE THREAD

**Issue by Bikasa** [DaSpawn/xlsx-stream-reader#2]
If I am putting two empty rows continuously  having cell values as empty string..My workbookreader  throwing the error saying '**missing Shared string**' .Is there any way to avoid this?
![error](https://cloud.githubusercontent.com/assets/23119692/19804937/11bd4848-9d2f-11e6-9f13-ccc83ddceccd.png)
![error2](https://cloud.githubusercontent.com/assets/23119692/19805021/8b2ea7d0-9d2f-11e6-940a-42892d269696.png)

**Comment by DaSpawn** [comment]
this error is actually related to issue #1 (the shared strings part of the xlsx is packed after the sheets in the xlsx), I am working on merging the solution shortly

**Comment by Bikasa** [comment]
Hi ,I have updated my node modules.But I am unable to get your changes.

**Comment by DaSpawn** [comment]
I have updated npmjs

**Comment by Bikasa** [comment]
Hi DaSpawn ,
 Thank you . I am able to get your updated code.But I am getting the same issue.When I am trying to import a sheet having last rows as empty string value ,it's 1st throwing an error saying "**missing shared string : 4**"  and then reads the row.I am unable to get Why its thorwing the error.The excell sheet that I have tried is like below screen shot.
![empty row](https://cloud.githubusercontent.com/assets/23119692/19885884/1b44bdb8-a047-11e6-9800-e55a9a384ab2.png)

Scenario 2 : When two empty rows is present in the middle of  two valued rows ,the 1st empty row picks the value from the last valued row 1st column and puts the others as empty and when I am reading the last valued row its 1st column gets empty value and other columns have their own values .Please find the below screen shot.
![error 2](https://cloud.githubusercontent.com/assets/23119692/19886353/d38d2832-a048-11e6-9f12-473ba9491f7e.png)

**Comment by Bikasa** [comment]
Hi DaSpawn ,
 Does the above senarios resolved in the build no 0.9.2.Because I am seeing the same issue as commented  above .Kindly let me know if those scenarios are resolve ?

**Comment by DaSpawn** [comment]
it appeared to be part of shared string issue which aborts processing (the "missing Shared string" error) but fixing that did not fix your issue.  Will dig further into this

**Comment by Bikasa** [comment]
Thank you @DaSpawn .Hope ,you'll get a fix soon based upon the above scenarios.

**Comment by DaSpawn** [comment]
please test with latest version (0.9.5)

**Comment by Bikasa** [comment]
Okay...ll test soon and get you back soon.

**Comment by Bikasa** [comment]
Thanks @DaSpawn .It's working as expected.

**Comment by DaSpawn** [comment]
Please note I just caught a mistake I mage trying to solve this issue which would cause numeric cells to not be returned, please update to at least 0.9.7
